CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    surname TEXT NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    nick VARCHAR(25) NOT NULL UNIQUE,
    password VARCHAR(60),
    verified BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    role BIGINT DEFAULT 1 NOT NULL REFERENCES roles(id)
);