CREATE TABLE email_verification_token(
     id BIGSERIAL PRIMARY KEY,
     token VARCHAR(36) UNIQUE NOT NULL,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
     expires_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP + INTERVAL '1 day') NOT NULL,
     used BOOLEAN DEFAULT FALSE NOT NULL,
     user_id BIGINT NOT NULL REFERENCES users(id)
)