CREATE TABLE refresh_token (
   id BIGSERIAL PRIMARY KEY,
   token VARCHAR(36) UNIQUE NOT NULL,
   revoked BOOLEAN DEFAULT FALSE NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   expires_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP + INTERVAL '7 day') NOT NULL,
   user_id BIGINT NOT NULL REFERENCES users(id)
)