spring.application.name=userauth

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=root

#Db migrations
spring.flyway.clean-disabled=false

#Logs in console
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.security=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true