name: Application Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD:  ${{ secrets.MAIL_PASSWORD }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: auth_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        service: [userauth]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.service }}-${{ hashFiles(format('{0}/pom.xml', matrix.service)) }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test with Maven
        run: mvn -f ${{ matrix.service}}/pom.xml clean verify

      - name: Jacoco report to pull request comment
        if: always()
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/${{ matrix.service }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-zone: 50

      - name: Deploy Jacoco HTML report to GitHub pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./jacoco-report/target/site/jacoco-aggregate
          publish_dir: ./${{ matrix.service }}/target/site/jacoco
          destination_dir: ${{ matrix.service }}
          publish_branch: gh-pages
          force_orphan: 'true'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}
          path: ${{ matrix.service }}/target/${{ matrix.service }}.jar

      - name: SonarQube analysis
        run: |
          mvn -f ${{ matrix.service }}/pom.xml sonar:sonar \
          -Dsonar.organization=${{ secrets.SONAR_ORG }} \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}-${{ matrix.service }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.projectBaseDir=${{ matrix.service }} \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  frontend_build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Create production .env file
        run: |
          echo "VITE_AUTH_API_URL=${{ secrets.PROD_AUTH_API_URL }}" > ./frontend/.env

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Force index.html over 404.html
        run: |
          cp ./frontend/dist/index.html ./frontend/dist/404.html

      - name: Deploy frontend to GitHub pages
        if: github.ref == 'refs/heads/main' && github.event.name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages
          destination_dir: .


  deploy:
    needs: build_and_test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL_DEPLOY }}
      DB_USERNAME: ${{ secrets.DB_USERNAME_DEPLOY }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEPLOY }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      APP_NAME_MAP: |
        {
          "userauth": "userauthapp"
        }

    strategy:
      matrix:
        service: [userauth]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.service }}

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Deploy ${{ matrix.service }} JAR to Microsoft Azure
        run: |
          APP_NAME=$(echo '${{ env.APP_NAME_MAP }}' | jq -r --arg svc "${{ matrix.service }}" '.[$svc]')
          echo "Deploying to: $APP_NAME"
          JAR=$(find . -name "${{ matrix.service }}.jar" | head -n 1)
          echo "Jar path is: $JAR"
          
          az webapp deploy \
          --resource-group FirstResourceGroup \
          --name $APP_NAME \
          --src-path $JAR \
          --type jar






